<a href="https://colab.research.google.com/github/Jenn2626/Python/blob/main/Clean_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df_sales = pd.read_csv('/content/sales_for _clean.csv')

In [4]:
df_sales.info()
df_sales.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   CustomerID  1025 non-null   int64
 1   JoinDate    1025 non-null   object
 2   Unused      0 non-null      float64
 3   Mobile      1025 non-null   float64
 4   Name        923 non-null    object
 5   Email       929 non-null    object
 6   Product     1025 non-null   object
 7   Scores      898 non-null    float64
 8   Birthdate   1025 non-null   object
 9   Revenue     1025 non-null   object
 10  Order_Date  1025 non-null   object
dtypes: float64(3), int64(1), object(7)
memory usage: 88.2+ KB

,CustomerID,JoinDate,Unused,Mobile,Name,Email,Product,Scores,Birthdate,Revenue,Order_Date
0,1,8/7/19,NaN,8.433361e+10,mIChAel mIcHALek,contact812@domain.com,Tablet,66.0,2/10/97,7877$,9/7/23
1,2,9/10/18,NaN,9.734441e+08,Andrew Jimenez,service45@example.com,table,53.0,8/23/71,6087$,1/9/23
2,3,20190630,NaN,3.382630e+08,Ann Gow,service699@test.com,SMARTPHONE,77.0,11/5/83,1105$,8/7/23
3,4,2019-09-06 00:00:1567702800,NaN,8.496607e+10,James Chen,customer575@example.com,table,58.0,12/21/98,1019$,7/27/23
4,5,20170812,NaN,8.476707e+10,Dollie Martinez,admin235@domain.com,Smartphone,NaN,8/25/05,2985$,10/5/23

In [6]:
# Convert to datetime
# Joindate datatype is timestamp, need to split lay date k lay time
df_sales['JoinDate'] = df_sales['JoinDate'].str.split().str[0]
df_sales

,CustomerID,JoinDate,Unused,Mobile,Name,Email,Product,Scores,Birthdate,Revenue,Order_Date
0,1,8/7/19,NaN,8.433361e+10,mIChAel mIcHALek,contact812@domain.com,Tablet,66.0,2/10/97,7877$,9/7/23
1,2,9/10/18,NaN,9.734441e+08,Andrew Jimenez,service45@example.com,table,53.0,8/23/71,6087$,1/9/23
2,3,20190630,NaN,3.382630e+08,Ann Gow,service699@test.com,SMARTPHONE,77.0,11/5/83,1105$,8/7/23
3,4,2019-09-06,NaN,8.496607e+10,James Chen,customer575@example.com,table,58.0,12/21/98,1019$,7/27/23
4,5,20170812,NaN,8.476707e+10,Dollie Martinez,admin235@domain.com,Smartphone,NaN,8/25/05,2985$,10/5/23
...,...,...,...,...,...,...,...,...,...,...,...
1020,1021,8/15/21,NaN,8.496412e+10,RubEN rAy,info613@test.com,tablet,54.0,12/29/77,8924$,4/8/23
1021,1022,6/8/21,NaN,8.435878e+10,tImoTHy wiLEY,admin191@example.com,Smartphone,84.0,2/2/74,1815$,2/14/23
1022,1023,7/2/22,NaN,8.476342e+10,ValaRiE EchoLS,service442@test.com,tablet,81.0,1/18/73,2148$,10/6/23
1023,1024,7/24/19,NaN,8.412880e+11,MArtA WOng,NaN,Smartphone,59.0,7/15/62,5127$,9/28/23
1024,1025,10/6/22,NaN,8.433743e+10,denNis rePiNE,contact528@domain.com,tablet,76.0,11/16/72,4006$,8/31/23

In [10]:
# Convert to datetime
date_col =['JoinDate','Birthdate','Order_Date']
for col in date_col:
  df_sales[col] = pd.to_datetime(df_sales[col])
df_sales.info()
df_sales.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   CustomerID  1025 non-null   int64
 1   JoinDate    1025 non-null   datetime64[ns]
 2   Unused      0 non-null      float64
 3   Mobile      1025 non-null   float64
 4   Name        923 non-null    object
 5   Email       929 non-null    object
 6   Product     1025 non-null   object
 7   Scores      898 non-null    float64
 8   Birthdate   1025 non-null   datetime64[ns]
 9   Revenue     1025 non-null   object
 10  Order_Date  1025 non-null   datetime64[ns]
dtypes: datetime64[ns](3), float64(3), int64(1), object(4)
memory usage: 88.2+ KB

,CustomerID,JoinDate,Unused,Mobile,Name,Email,Product,Scores,Birthdate,Revenue,Order_Date
0,1,2019-08-07,NaN,8.433361e+10,mIChAel mIcHALek,contact812@domain.com,Tablet,66.0,1997-02-10,7877$,2023-09-07
1,2,2018-09-10,NaN,9.734441e+08,Andrew Jimenez,service45@example.com,table,53.0,2071-08-23,6087$,2023-01-09
2,3,2019-06-30,NaN,3.382630e+08,Ann Gow,service699@test.com,SMARTPHONE,77.0,1983-11-05,1105$,2023-08-07
3,4,2019-09-06,NaN,8.496607e+10,James Chen,customer575@example.com,table,58.0,1998-12-21,1019$,2023-07-27
4,5,2017-08-12,NaN,8.476707e+10,Dollie Martinez,admin235@domain.com,Smartphone,NaN,2005-08-25,2985$,2023-10-05

In [12]:
# Conver to numeric
df_sales['Revenue'] = df_sales['Revenue'].str.replace('$','')
df_sales['Revenue'] = pd.to_numeric(df_sales['Revenue'])
df_sales.head(5)

,CustomerID,JoinDate,Unused,Mobile,Name,Email,Product,Scores,Birthdate,Revenue,Order_Date
0,1,2019-08-07,NaN,8.433361e+10,mIChAel mIcHALek,contact812@domain.com,Tablet,66.0,1997-02-10,7877,2023-09-07
1,2,2018-09-10,NaN,9.734441e+08,Andrew Jimenez,service45@example.com,table,53.0,2071-08-23,6087,2023-01-09
2,3,2019-06-30,NaN,3.382630e+08,Ann Gow,service699@test.com,SMARTPHONE,77.0,1983-11-05,1105,2023-08-07
3,4,2019-09-06,NaN,8.496607e+10,James Chen,customer575@example.com,table,58.0,1998-12-21,1019,2023-07-27
4,5,2017-08-12,NaN,8.476707e+10,Dollie Martinez,admin235@domain.com,Smartphone,NaN,2005-08-25,2985,2023-10-05

In [13]:
# Convert to string
str_col =['CustomerID','Mobile']
for col in str_col:
  df_sales[col] = df_sales[col].astype(str)
df_sales.head(5)

,CustomerID,JoinDate,Unused,Mobile,Name,Email,Product,Scores,Birthdate,Revenue,Order_Date
0,1,2019-08-07,NaN,84333605993.0,mIChAel mIcHALek,contact812@domain.com,Tablet,66.0,1997-02-10,7877,2023-09-07
1,2,2018-09-10,NaN,973444062.0,Andrew Jimenez,service45@example.com,table,53.0,2071-08-23,6087,2023-01-09
2,3,2019-06-30,NaN,338262954.0,Ann Gow,service699@test.com,SMARTPHONE,77.0,1983-11-05,1105,2023-08-07
3,4,2019-09-06,NaN,84966068026.0,James Chen,customer575@example.com,table,58.0,1998-12-21,1019,2023-07-27
4,5,2017-08-12,NaN,84767065885.0,Dollie Martinez,admin235@domain.com,Smartphone,NaN,2005-08-25,2985,2023-10-05

In [16]:
# Convert Mobile
# Split
df_sales['Mobile'] = df_sales['Mobile'].str.split('.').str[0]
df_sales.head(5)

,CustomerID,JoinDate,Unused,Mobile,Name,Email,Product,Scores,Birthdate,Revenue,Order_Date
0,1,2019-08-07,NaN,84333605993,mIChAel mIcHALek,contact812@domain.com,Tablet,66.0,1997-02-10,7877,2023-09-07
1,2,2018-09-10,NaN,973444062,Andrew Jimenez,service45@example.com,table,53.0,2071-08-23,6087,2023-01-09
2,3,2019-06-30,NaN,338262954,Ann Gow,service699@test.com,SMARTPHONE,77.0,1983-11-05,1105,2023-08-07
3,4,2019-09-06,NaN,84966068026,James Chen,customer575@example.com,table,58.0,1998-12-21,1019,2023-07-27
4,5,2017-08-12,NaN,84767065885,Dollie Martinez,admin235@domain.com,Smartphone,NaN,2005-08-25,2985,2023-10-05

In [21]:

# Condition add '84' in Mobile
def clean_mobile(x):
  if x.startswith('84'):
    return x
  else:
    return '84' + x
df_sales['Mobile'] = df_sales['Mobile'].apply(clean_mobile)
df_sales.head(5)

,CustomerID,JoinDate,Unused,Mobile,Name,Email,Product,Scores,Birthdate,Revenue,Order_Date
0,1,2019-08-07,NaN,84333605993,mIChAel mIcHALek,contact812@domain.com,Tablet,66.0,1997-02-10,7877,2023-09-07
1,2,2018-09-10,NaN,84973444062,Andrew Jimenez,service45@example.com,table,53.0,2071-08-23,6087,2023-01-09
2,3,2019-06-30,NaN,84338262954,Ann Gow,service699@test.com,SMARTPHONE,77.0,1983-11-05,1105,2023-08-07
3,4,2019-09-06,NaN,84966068026,James Chen,customer575@example.com,table,58.0,1998-12-21,1019,2023-07-27
4,5,2017-08-12,NaN,84767065885,Dollie Martinez,admin235@domain.com,Smartphone,NaN,2005-08-25,2985,2023-10-05

In [22]:
#Convert Name
df_sales['Name'] = df_sales['Name'].str.title()
df_sales.head(5)

,CustomerID,JoinDate,Unused,Mobile,Name,Email,Product,Scores,Birthdate,Revenue,Order_Date
0,1,2019-08-07,NaN,84333605993,Michael Michalek,contact812@domain.com,Tablet,66.0,1997-02-10,7877,2023-09-07
1,2,2018-09-10,NaN,84973444062,Andrew Jimenez,service45@example.com,table,53.0,2071-08-23,6087,2023-01-09
2,3,2019-06-30,NaN,84338262954,Ann Gow,service699@test.com,SMARTPHONE,77.0,1983-11-05,1105,2023-08-07
3,4,2019-09-06,NaN,84966068026,James Chen,customer575@example.com,table,58.0,1998-12-21,1019,2023-07-27
4,5,2017-08-12,NaN,84767065885,Dollie Martinez,admin235@domain.com,Smartphone,NaN,2005-08-25,2985,2023-10-05

In [23]:
# Convert Product
# Count values product to know how product category
df_sales['Product'].value_counts()

Product
 SMARTPHONE     178
Tablet          176
Smartphone      172
Laptop          169
Laptop          165
tablet          148
table             8
Smart phone       4
Lap               3
 SMAR TPHONE      1
Table             1
Name: count, dtype: int64

In [24]:
# Strip blank
df_sales['Product'] = df_sales['Product'].str.strip()
df_sales['Product'].value_counts()

Product
Laptop         334
SMARTPHONE     178
Tablet         176
Smartphone     172
tablet         148
table            8
Smart phone      4
Lap              3
SMAR TPHONE      1
Table            1
Name: count, dtype: int64

In [25]:
df_sales['Product']= df_sales['Product'].str.title()
df_sales['Product'].value_counts()

Product
Smartphone     350
Laptop         334
Tablet         324
Table            9
Smart Phone      4
Lap              3
Smar Tphone      1
Name: count, dtype: int64

In [27]:
# Condition logic
def clean_Product(x):
  if x in ['Smart Phone','Smar Tphone']:
    return 'Smartphone'
  elif x in ['Lap']:
    return 'Laptop'
  elif x in ['Table']:
    return 'Tablet'
  else:
    return x
df_sales['Product'] = df_sales['Product'].apply(clean_Product)
df_sales['Product'].value_counts()

Product
Smartphone    355
Laptop        337
Tablet        333
Name: count, dtype: int64

In [28]:
df_sales.head(5)

,CustomerID,JoinDate,Unused,Mobile,Name,Email,Product,Scores,Birthdate,Revenue,Order_Date
0,1,2019-08-07,NaN,84333605993,Michael Michalek,contact812@domain.com,Tablet,66.0,1997-02-10,7877,2023-09-07
1,2,2018-09-10,NaN,84973444062,Andrew Jimenez,service45@example.com,Tablet,53.0,2071-08-23,6087,2023-01-09
2,3,2019-06-30,NaN,84338262954,Ann Gow,service699@test.com,Smartphone,77.0,1983-11-05,1105,2023-08-07
3,4,2019-09-06,NaN,84966068026,James Chen,customer575@example.com,Tablet,58.0,1998-12-21,1019,2023-07-27
4,5,2017-08-12,NaN,84767065885,Dollie Martinez,admin235@domain.com,Smartphone,NaN,2005-08-25,2985,2023-10-05

In [30]:
# Create find missing data function
def find_missing_value(df):
  missing_data = df.isnull().sum().to_frame('count_null')
  missing_data['percent_null'] = missing_data['count_null']/len(missing_data)
  return missing_data
find_missing_value(df_sales)
#

            count_null  percent_null
CustomerID           0      0.000000
JoinDate             0      0.000000
Unused            1025     93.181818
Mobile               0      0.000000
Name               102      9.272727
Email               96      8.727273
Product              0      0.000000
Scores             127     11.545455
Birthdate            0      0.000000
Revenue              0      0.000000
Order_Date           0      0.000000

In [31]:
# Drop Unused
df_sales = df_sales.drop(columns='Unused')
df_sales.head(5)

,CustomerID,JoinDate,Mobile,Name,Email,Product,Scores,Birthdate,Revenue,Order_Date
0,1,2019-08-07,84333605993,Michael Michalek,contact812@domain.com,Tablet,66.0,1997-02-10,7877,2023-09-07
1,2,2018-09-10,84973444062,Andrew Jimenez,service45@example.com,Tablet,53.0,2071-08-23,6087,2023-01-09
2,3,2019-06-30,84338262954,Ann Gow,service699@test.com,Smartphone,77.0,1983-11-05,1105,2023-08-07
3,4,2019-09-06,84966068026,James Chen,customer575@example.com,Tablet,58.0,1998-12-21,1019,2023-07-27
4,5,2017-08-12,84767065885,Dollie Martinez,admin235@domain.com,Smartphone,NaN,2005-08-25,2985,2023-10-05

In [45]:
# Find duplicate by each row

df_sales[df_sales.duplicated()]

Empty DataFrame
Columns: [CustomerID, JoinDate, Mobile, Name, Email, Product, Scores, Birthdate, Revenue, Order_Date]
Index: []

In [46]:
# Find duplicate by 1 column
df_sales[df_sales['CustomerID'].duplicated()]

,CustomerID,JoinDate,Mobile,Name,Email,Product,Scores,Birthdate,Revenue,Order_Date
14,15,2018-04-18,841267000000,NaN,NaN,Tablet,61.0,2064-05-22,1041,2023-05-09
24,22,2019-09-02,84978909747,NaN,contact159@example.com,Tablet,75.0,2066-04-05,5514,2023-05-29
32,27,2019-07-23,84974404339,Lawrence Cummings,NaN,Smartphone,73.0,1993-05-17,5195,2023-08-16
42,42,2018-10-18,841288000000,NaN,admin576@test.com,Tablet,100.0,1994-11-17,7141,2023-07-19

In [47]:
# Show up all row duplicate  check by CustomerID
df_sales[df_sales['CustomerID'].duplicated(keep = False)]

,CustomerID,JoinDate,Mobile,Name,Email,Product,Scores,Birthdate,Revenue,Order_Date
13,15,2017-12-10,84356173988,Paul Ruper,admin929@domain.com,Tablet,76.91,1998-11-15,433,2023-11-29
14,15,2018-04-18,841267000000,NaN,NaN,Tablet,61.00,2064-05-22,1041,2023-05-09
21,22,2018-05-28,84334263580,Laura Beatty,admin179@domain.com,Smartphone,88.00,1985-01-18,9023,2023-08-28
24,22,2019-09-02,84978909747,NaN,contact159@example.com,Tablet,75.00,2066-04-05,5514,2023-05-29
26,27,2018-03-21,841266000000,James Johnson,contact660@example.com,Tablet,64.00,2069-12-21,410,2023-04-23
32,27,2019-07-23,84974404339,Lawrence Cummings,NaN,Smartphone,73.00,1993-05-17,5195,2023-08-16
41,42,2019-05-21,841266000000,NaN,service300@test.com,Smartphone,76.91,2060-12-21,8380,2023-09-01
42,42,2018-10-18,841288000000,NaN,admin576@test.com,Tablet,100.00,1994-11-17,7141,2023-07-19

In [49]:
# Drop duplicate by method keep the last one
df_sales = df_sales.drop_duplicates('CustomerID',keep = 'last')
df_sales[df_sales['CustomerID'].duplicated(keep = False)]

Empty DataFrame
Columns: [CustomerID, JoinDate, Mobile, Name, Email, Product, Scores, Birthdate, Revenue, Order_Date]
Index: []

In [32]:
# Define function find missing value
def find_missing_value(df):
  missing_data = df.isnull().sum().to_frame('count_null')
  missing_data['percent_null'] = missing_data['count_null']/len(missing_data)
  return missing_data
find_missing_value(df_sales)

            count_null  percent_null
CustomerID           0           0.0
JoinDate             0           0.0
Mobile               0           0.0
Name               102          10.2
Email               96           9.6
Product              0           0.0
Scores             127          12.7
Birthdate            0           0.0
Revenue              0           0.0
Order_Date           0           0.0

In [37]:
# Input missing data in column 'score' by mean score


df_sales['Scores']=df_sales['Scores'].fillna(df_sales['Scores'].mean())
df_sales['Scores'] = df_sales['Scores'].round(2)
df_sales.head(5)

,CustomerID,JoinDate,Mobile,Name,Email,Product,Scores,Birthdate,Revenue,Order_Date
0,1,2019-08-07,84333605993,Michael Michalek,contact812@domain.com,Tablet,66.00,1997-02-10,7877,2023-09-07
1,2,2018-09-10,84973444062,Andrew Jimenez,service45@example.com,Tablet,53.00,2071-08-23,6087,2023-01-09
2,3,2019-06-30,84338262954,Ann Gow,service699@test.com,Smartphone,77.00,1983-11-05,1105,2023-08-07
3,4,2019-09-06,84966068026,James Chen,customer575@example.com,Tablet,58.00,1998-12-21,1019,2023-07-27
4,5,2017-08-12,84767065885,Dollie Martinez,admin235@domain.com,Smartphone,76.91,2005-08-25,2985,2023-10-05

In [38]:
find_missing_value(df_sales)

            count_null  percent_null
CustomerID           0           0.0
JoinDate             0           0.0
Mobile               0           0.0
Name               102          10.2
Email               96           9.6
Product              0           0.0
Scores               0           0.0
Birthdate            0           0.0
Revenue              0           0.0
Order_Date           0           0.0