<a href="https://colab.research.google.com/github/Jenn2626/Python/blob/main/Condition_Logic_%26_Concact_%26_Join.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
df_customers =pd.read_csv('/content/customers.csv')
df_orders_items = pd.read_csv('/content/order_items.csv')
df_orders = pd.read_csv('/content/orders.csv')
df_products = pd.read_csv('/content/products.csv')
df_sellers = pd.read_csv('/content/sellers.csv')
df_geolocation = pd.read_csv('/content/geolocation.csv')
df_order_payments = pd.read_csv('/content/order_payments.csv')
df_order_reviews = pd.read_csv('/content/order_reviews.csv')
df_product_category_name_translation = pd.read_csv('/content/product_category_name_translation.csv')
#

In [9]:
# Condition Logic
def freight_value_category(x):
  if x < 15:
    return 'Cheap'
  elif 15 <= x < 25:
    return 'Medium'
  else:
    return 'Expensive'

df_orders_items['freight_value_category'] = df_orders_items['freight_value'].apply(freight_value_category)
df_orders_items

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,freight_value_category
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,Cheap
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,Medium
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,Medium
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,Cheap
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,Medium
...,...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41,Expensive
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53,Expensive
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95,Medium
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72,Cheap
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79,Cheap

In [10]:
# Lambda:

df_orders_items['freight_value_category'] = df_orders_items['freight_value'].apply(lambda x :'Cheap'if x < 15 else('Midium'if x< 25 else 'Expensive'))
df_orders_items

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,freight_value_category
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,Cheap
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,Midium
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,Midium
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,Cheap
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,Midium
...,...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41,Expensive
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53,Expensive
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95,Midium
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72,Cheap
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79,Cheap

In [19]:
# 2 or more conditions
def discount_category(row):
  if row['price'] > 200:
    if row['freight_value'] > 50:
      return 0.2
    else:
      return 0.1
  else:
    if 100 <= row['price'] <= 200:
      if row['freight_value'] > 50:
        return 0.15
      else:
        return 0.05
  return 0

df_orders_items['category']= df_orders_items.apply(discount_category,axis = 1)
df_orders_items

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,freight_value_category,discount_category,category
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,Cheap,0.00,0.00
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,Midium,0.10,0.10
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,Midium,0.05,0.05
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,Cheap,0.00,0.00
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,Midium,0.05,0.05
...,...,...,...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41,Expensive,0.10,0.10
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53,Expensive,0.10,0.10
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95,Midium,0.00,0.00
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72,Cheap,0.00,0.00
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79,Cheap,0.00,0.00

1. Calculate total value = price + freight_value
2. Category total value by mehod:
  total > 500  is hight
  200 < total < 500 is medium
  total < 200 is low

In [23]:
df_orders_items['total_value'] = df_orders_items['price'] + df_orders_items['freight_value']

df_orders_items

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,freight_value_category,discount_category,category,total_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,Cheap,0.00,0.00,72.19
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,Midium,0.10,0.10,259.83
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,Midium,0.05,0.05,216.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,Cheap,0.00,0.00,25.78
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,Midium,0.05,0.05,218.04
...,...,...,...,...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41,Expensive,0.10,0.10,343.40
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53,Expensive,0.10,0.10,386.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95,Midium,0.00,0.00,116.85
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72,Cheap,0.00,0.00,64.71
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79,Cheap,0.00,0.00,55.79

In [25]:
def total_category(x):
  if x > 500:
    return 'High'
  elif 200 < x < 500:
    return 'Medium'
  else:
    return 'Low'

df_orders_items['total_value_category']=df_orders_items['total_value'].apply(total_category)
df_orders_items

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,freight_value_category,discount_category,category,total_value,total_value_category
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,Cheap,0.00,0.00,72.19,Low
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,Midium,0.10,0.10,259.83,Medium
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,Midium,0.05,0.05,216.87,Medium
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,Cheap,0.00,0.00,25.78,Low
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,Midium,0.05,0.05,218.04,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41,Expensive,0.10,0.10,343.40,Medium
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53,Expensive,0.10,0.10,386.53,Medium
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95,Midium,0.00,0.00,116.85,Low
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72,Cheap,0.00,0.00,64.71,Low
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79,Cheap,0.00,0.00,55.79,Low

In [34]:
dfs = [df_product_category_name_translation, df_customers, df_geolocation, df_orders_items, df_orders, df_order_payments,
       df_products, df_order_reviews, df_sellers]
df_names = ['df_product_category_name_translation', 'df_customers', 'df_geolocation', 'df_orders_items', 'df_orders',
            'df_order_payments', 'df_products', 'df_order_reviews', 'df_sellers']

summary_data = []

# Dùng phương thức apply để lấy thông tin cho từng bảng
for df, name in zip(dfs, df_names):
    shape = df.shape  # (số dòng, số cột)
    columns = list(df.columns)  # Tên các cột
    summary_data.append({
        'Tên bảng': name,
        'Shape': shape,
        'Tên cột': columns,
    })

# Tạo DataFrame từ thông tin tổng hợp
summary_df = pd.DataFrame(summary_data)
summary_df

,Tên bảng,Shape,Tên cột
0,df_product_category_name_translation,"(71, 2)","[product_category_name, product_category_name_..."
1,df_customers,"(99441, 5)","[customer_id, customer_unique_id, customer_zip..."
2,df_geolocation,"(1000163, 5)","[geolocation_zip_code_prefix, geolocation_lat,..."
3,df_orders_items,"(112650, 12)","[order_id, order_item_id, product_id, seller_i..."
4,df_orders,"(99441, 8)","[order_id, customer_id, order_status, order_pu..."
5,df_order_payments,"(103886, 5)","[order_id, payment_sequential, payment_type, p..."
6,df_products,"(32951, 9)","[product_id, product_category_name, product_na..."
7,df_order_reviews,"(99224, 7)","[review_id, order_id, review_score, review_com..."
8,df_sellers,"(3095, 4)","[seller_id, seller_zip_code_prefix, seller_cit..."

# JOIN
1. join giữa các bảng orders, order_items, và customer
2. Tính tổng price và freight_value theo từng customer_state và order_status

In [39]:
import pandas as pd
merge_customer = pd.merge(df_customers, df_orders, how='left', on='customer_id')
merge_customer_order_items = pd.merge(merge_customer, df_orders_items, how='left', on='order_id')

merge_customer_order_items.groupby(['customer_state','order_status']).agg(total_price = ('price','sum'), total_freight_value = ('freight_value', 'sum')).reset_index()

    customer_state order_status  total_price  total_freight_value
0               AC    delivered     15930.97              3644.36
1               AC      shipped        51.98                42.39
2               AL     canceled         0.00                 0.00
3               AL    delivered     78855.72             15316.77
4               AL     invoiced       108.75                63.36
..             ...          ...          ...                  ...
144             TO     canceled       213.75                36.82
145             TO    delivered     48402.51             11604.86
146             TO   processing        79.00                17.98
147             TO      shipped       926.48                73.02
148             TO  unavailable         0.00                 0.00

[149 rows x 4 columns]