<a href="https://colab.research.google.com/github/Jenn2626/Python/blob/main/DataFrames.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Load Data

In [47]:
import pandas as pd

# Load data from CSV files
df_customers = pd.read_csv('/content/customers.csv')
df_orders = pd.read_csv('/content/orders.csv')
df_order_items = pd.read_csv('/content/order_items.csv')
df_product = pd.read_csv('/content/products.csv')
df_seller = pd.read_csv('/content/sellers.csv')
df_product_category_name_translation = pd.read_csv('/content/product_category_name_translation.csv')
df_order_reviews = pd.read_csv('/content/order_reviews.csv')
df_geolocation = pd.read_csv('/content/geolocation.csv')
df_order_payments = pd.read_csv('/content/order_payments.csv')

In [25]:
# Overview data
# 1. Xem 5 dòng đầu
df_customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [26]:
# Overview data
# 1. Xem 5 dòng cuối
df_customers.tail()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP

In [27]:
# Overview data
# 1. Xem 5 dòng bất kỳ
df_customers.sample(5)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
67639,6b44ea99d4cb9ebdb1a80994a7317728,00377a18050b898b93e2c774be9947db,78065,cuiaba,MT
59559,33815697efba93373844bb3d49166e43,7429244afc9e9046e0c8b3603162eab8,13401,piracicaba,SP
11806,e43a8c4a2cacc15e45d6a73beb2ee7e8,3e2662d873c55f390786c29319aaaeac,12952,atibaia,SP
76684,6aa501436836de38051dfc5fce054127,d2cdc1bc229c5e1848f8f7ce60a415f7,6823,embu das artes,SP
97137,3416e45f6c9842bfc863fe211e22a261,36f8e4ca148a3c0916e6233c825b13c0,4662,sao paulo,SP

In [29]:
# Overview data
# 1. Xem cấu trúc
df_customers.shape

(99441, 5)

In [30]:
# Overview data
# 1. Xem định dạng
df_customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

# 2. Filtering Challenge
a. Lọc các đánh giá trong bảng order_reviews_dataset có điểm review_score nằm trong khoảng từ 2 đến 4.

b. Lọc các đơn hàng trong bảng orders_dataset có trạng thái là delivered và order_purchase_timestamp thuộc năm 2018.

c. Trong bảng order_items_dataset, loại bỏ các bản ghi trùng lặp dựa trên order_id và product_id, vì có thể có nhiều bản ghi cho cùng một order_id nhưng các sản phẩm khác nhau.

In [36]:
# 1. Lọc các đánh giá trong bảng order_reviews_dataset có điểm review_score nằm trong khoảng từ 2 đến 4.
# df_order_reviews.head()
# df_order_reviews['review_score'].between(2,4)
df_order_reviews[df_order_reviews['review_score'].between(2,4)]

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
9,8670d52e15e00043ae7de4c01cc2fe06,b9bf720beb4ab3728760088589c62129,4,recomendo,aparelho eficiente. no site a marca do aparelh...,2018-05-22 00:00:00,2018-05-23 16:45:47
12,4b49719c8a200003f700d3d986ea1a19,9d6f15f95d01e79bd1349cc208361f09,4,NaN,"Mas um pouco ,travando...pelo valor ta Boa.\r\n",2018-02-16 00:00:00,2018-02-20 10:52:22
13,23f75a37effc35d9a915b4e1ad483793,2eaf8e099d871cd5c22b83b5ea8f6e0e,4,NaN,NaN,2018-03-28 00:00:00,2018-03-30 15:10:55
14,9a0abbb668bafb95a6d2b05db43284c4,d7bd0e4afdf94846eb73642b4e3e75c3,3,NaN,NaN,2017-04-30 00:00:00,2017-05-03 00:02:22
...,...,...,...,...,...,...,...
99205,98fffa80dc9acbde7388bef1600f3b15,d398e9c82363c12527f71801bf0e6100,4,NaN,para este produto recebi de acordo com a compr...,2017-11-29 00:00:00,2017-11-30 15:52:51
99212,3ea12859f456855149b564d1a221f87a,f62f01ec64c6b221f926ba560907d8f7,3,NaN,NaN,2017-04-05 00:00:00,2017-04-05 09:42:58
99215,a709d176f59bc3af77f4149c96bae357,d5cb12269711bd1eaf7eed8fd32a7c95,3,NaN,"O produto não foi enviado com NF, não existe v...",2018-05-19 00:00:00,2018-05-20 21:51:06
99216,115d72425fc59eec9a2e9d7594c6d93d,acd45245723df7cb52772a34416b41b1,3,NaN,NaN,2018-05-08 00:00:00,2018-05-10 14:37:03
99222,1adeb9d84d72fe4e337617733eb85149,7725825d039fc1f0ceb7635e3f7d9206,4,NaN,NaN,2018-07-01 00:00:00,2018-07-02 12:59:13

In [52]:
# 2. Lọc các đơn hàng trong bảng orders_dataset có trạng thái là delivered và order_purchase_timestamp thuộc năm 2018.
# (df_orders['order_status'].isin(['delivered']))
# (df_orders['order_purchase_timestamp'] >'2017-12-31')
# ((df_orders['order_purchase_timestamp'] <'2018-01-01'))
df_orders[(df_orders['order_status'].isin(['delivered'])) & ((df_orders['order_purchase_timestamp'] >'2017-12-31')) & (((df_orders['order_purchase_timestamp'] <'2018-01-01')))]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
3230,35298b52820bdcc64b7bf71ccc28a36c,52496ddf0025f7b0ec3cb640a97990f8,delivered,2017-12-31 19:28:24,2017-12-31 19:46:47,2018-01-03 17:34:11,2018-01-09 19:38:13,2018-02-09 00:00:00
8853,b6133255f440562f2b6d004d1b24743d,3ca973130cd813782697a76c95a6c480,delivered,2017-12-31 11:38:28,2018-01-03 04:29:36,2018-01-03 21:38:34,2018-01-05 18:55:46,2018-01-18 00:00:00
9058,6d9c9cea658be290a4d3c6ee16858ea9,f1eece538627fa853a59e6ebe3aa005e,delivered,2017-12-31 16:37:29,2017-12-31 16:47:17,2018-01-04 12:16:44,2018-01-25 18:43:18,2018-02-02 00:00:00
11048,ea4379fe06f33b88de9ffd4fcdddd6ba,d98a954d2c0d995688a33b6f8b73bb56,delivered,2017-12-31 00:30:41,2018-01-03 04:12:37,2018-01-04 20:32:15,2018-01-11 18:57:27,2018-01-18 00:00:00
11389,9a1925c9ea26df1c4bf618fdd4ebc943,ecf69e0cf3882d637727d4708ad34d4e,delivered,2017-12-31 14:37:51,2017-12-31 14:47:29,2018-01-03 17:38:47,2018-01-05 20:10:41,2018-01-30 00:00:00
...,...,...,...,...,...,...,...,...
91040,89ed06112208a473f65e0f9f40fc5af5,69882ae486f29c5155bde6d028532fe2,delivered,2017-12-31 08:36:11,2017-12-31 08:46:45,2018-01-02 19:26:50,2018-01-26 21:12:22,2018-01-30 00:00:00
92067,6a267276cd5ace781320f1239bb2f413,6723d41fcf93098e63aac8df2fcfae1a,delivered,2017-12-31 11:56:14,2017-12-31 12:08:24,2018-01-02 14:32:50,2018-01-10 15:29:01,2018-02-01 00:00:00
93536,b8fde15d11aff23b07a6081d8a7652aa,76f07d247039cd77e1cc89cebcf82aa5,delivered,2017-12-31 13:55:55,2017-12-31 14:06:50,2018-01-02 18:09:08,2018-01-08 19:33:47,2018-01-26 00:00:00
95971,bfde1814043e239cb93af22b6b09214b,f10f70292bca6ab2abd34b96b08d312d,delivered,2017-12-31 18:35:45,2017-12-31 18:46:40,2018-01-03 17:10:44,2018-01-24 02:24:13,2018-02-05 00:00:00
96695,da286fe249fa752e4b234df260764f06,4bc3f8a7ff21c10b55dda45c89ffc21e,delivered,2017-12-31 01:51:49,2017-12-31 02:06:54,2018-01-04 23:58:54,2018-01-08 22:43:12,2018-01-24 00:00:00

In [50]:

""" 3. Trong bảng order_items_dataset,
loại bỏ các bản ghi trùng lặp dựa trên order_id và product_id,
vì có thể có nhiều bản ghi cho cùng một order_id nhưng các sản phẩm khác nhau."""

# df_order_items.info()

df_order_items[['order_id','product_id']].drop_duplicates()

                                order_id                        product_id
0       00010242fe8c5a6d1ba2dd792cb16214  4244733e06e7ecb4970a6e2683c13e61
1       00018f77f2f0320c557190d7a144bdd3  e5f2d52b802189ee658865ca93d83a8f
2       000229ec398224ef6ca0657da4fc703e  c777355d18b72b67abbeef9df44fd0fd
3       00024acbcdf0a6daa1e931b038114c75  7634da152a4610f1595efa32f14722fc
4       00042b26cf59d7ce69dfabb4e55b4fd9  ac6c3623068f30de03045865e4e10089
...                                  ...                               ...
112645  fffc94f6ce00a00581880bf54a75a037  4aa6014eceb682077f9dc4bffebc05b0
112646  fffcd46ef2263f404302a634eb57f7eb  32e07fd915822b0765e448c4dd74c828
112647  fffce4705a9662cd70adb13d4a31832d  72a30483855e2eafc67aee5dc2560482
112648  fffe18544ffabc95dfada21779c9644f  9c422a519119dcad7575db5af1ba540e
112649  fffe41c64501cc87c801fd61db3f6244  350688d9dc1e75ff97be326363655e01

[102425 rows x 2 columns]

# 3. Sort DataFrame
## a. Sort by a Single Column
## b. Sort by Multiple Column

In [55]:
""" Sắp xếp order theo price  Z-A """
# df_order_items.info()
df_order_items.sort_values('price',ascending=False)[['order_id','price']]

                                order_id    price
3556    0812eb902a67711a1cb742b3cdaa65ae  6735.00
112233  fefacc66af859508bf1a7934eab1e97f  6729.00
107841  f5136e38d1a14a4dbd87dff67da82701  6499.00
74336   a96610ab360d42a2e5335a3998b4718a  4799.00
11249   199af31afc78c699f0dbf71fb178d4d4  4690.00
...                                  ...      ...
57300   8272b63d03f5f79c56e9e4120aec44ef     1.20
57307   8272b63d03f5f79c56e9e4120aec44ef     1.20
48625   6e864b3f0ec71031117ad4cf46b7f2a1     0.85
27652   3ee6513ae7ea23bdfab5b9ab60bffcb5     0.85
87081   c5bdd8ef3c0ec420232e668302179113     0.85

[112650 rows x 2 columns]

In [60]:
""" Sắp xếp order theo price  ZA, freight_value AZ """

df_order_items.sort_values(['price','freight_value'], ascending=[False,True]) [['order_id','price','freight_value']]

                                order_id    price  freight_value
3556    0812eb902a67711a1cb742b3cdaa65ae  6735.00         194.31
112233  fefacc66af859508bf1a7934eab1e97f  6729.00         193.21
107841  f5136e38d1a14a4dbd87dff67da82701  6499.00         227.66
74336   a96610ab360d42a2e5335a3998b4718a  4799.00         151.34
11249   199af31afc78c699f0dbf71fb178d4d4  4690.00          74.34
...                                  ...      ...            ...
57315   8272b63d03f5f79c56e9e4120aec44ef     1.20           7.89
57316   8272b63d03f5f79c56e9e4120aec44ef     1.20           7.89
27652   3ee6513ae7ea23bdfab5b9ab60bffcb5     0.85          18.23
48625   6e864b3f0ec71031117ad4cf46b7f2a1     0.85          18.23
87081   c5bdd8ef3c0ec420232e668302179113     0.85          22.30

[112650 rows x 3 columns]

# 4. Mathetics Operator
## a. Pandas Operator
## b. Using Numpy Function

In [64]:
# Tính tổng giá trị đơn hàng gồm price và freight value
df_order_items['total'] = df_order_items['price'] + df_order_items['freight_value']
df_order_items

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,total
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,72.19
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,259.83
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,216.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,25.78
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,218.04
...,...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41,343.40
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53,386.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95,116.85
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72,64.71
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79,55.79

In [65]:
# Tính diff price và freight value
df_order_items['diff'] = df_order_items['price'] - df_order_items['freight_value']
df_order_items

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,total,diff
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,72.19,45.61
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,259.83,219.97
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,216.87,181.13
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,25.78,0.20
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,218.04,181.76
...,...,...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41,343.40,256.58
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53,386.53,313.47
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95,116.85,82.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72,64.71,47.27
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79,55.79,30.21

In [67]:
# Tính tổng giá trị đơn hàng gồm price +3 và freight value
df_order_items['new_total'] = df_order_items['price'] + 3+ df_order_items['freight_value']
df_order_items

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,total,diff,new_total
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,72.19,45.61,75.19
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,259.83,219.97,262.83
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,216.87,181.13,219.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,25.78,0.20,28.78
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,218.04,181.76,221.04
...,...,...,...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41,343.40,256.58,346.40
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53,386.53,313.47,389.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95,116.85,82.95,119.85
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72,64.71,47.27,67.71
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79,55.79,30.21,58.79

## b. Using Numpy Function
> round, ceil, floor, abs...

In [72]:
import numpy as np
df_order_items['total_round'] = np.round(df_order_items['total'],1)
df_order_items

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,total,diff,new_total,total_round
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,72.19,45.61,75.19,72.2
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,259.83,219.97,262.83,259.8
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,216.87,181.13,219.87,216.9
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,25.78,0.20,28.78,25.8
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,218.04,181.76,221.04,218.0
...,...,...,...,...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41,343.40,256.58,346.40,343.4
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53,386.53,313.47,389.53,386.5
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95,116.85,82.95,119.85,116.8
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72,64.71,47.27,67.71,64.7
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79,55.79,30.21,58.79,55.8

#. Mathetics Challenge
1. Giả sử cửa hàng áp dụng khuyến mãi giảm giá 15% cho mỗi sản phẩm. Tạo một cột mới discounted_price để lưu giá trị price sau khi giảm 15%.

2. Tạo một cột mới savings để lưu số tiền tiết kiệm được sau khi áp dụng khuyến mãi. Đây chính là phần chênh lệch giữa price và discounted_price.

In [79]:
df_order_items['discounted_price'] = np.round(df_order_items['price']*0.85,2)
df_order_items

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,total,diff,new_total,total_round,discounted_price,savings
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,72.19,45.61,75.19,72.2,50.06,8.84
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,259.83,219.97,262.83,259.8,203.92,35.99
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,216.87,181.13,219.87,216.9,169.15,29.85
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,25.78,0.20,28.78,25.8,11.04,1.95
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,218.04,181.76,221.04,218.0,169.92,29.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41,343.40,256.58,346.40,343.4,254.99,45.00
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53,386.53,313.47,389.53,386.5,297.50,52.50
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95,116.85,82.95,119.85,116.8,84.92,14.98
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72,64.71,47.27,67.71,64.7,47.59,8.40
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79,55.79,30.21,58.79,55.8,36.55,6.45

In [78]:
df_order_items['savings'] = np.round(df_order_items['price'] - df_order_items['discounted_price'],2)
df_order_items

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,total,diff,new_total,total_round,discounted_price,savings
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,72.19,45.61,75.19,72.2,50.0650,8.84
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,259.83,219.97,262.83,259.8,203.9150,35.99
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,216.87,181.13,219.87,216.9,169.1500,29.85
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,25.78,0.20,28.78,25.8,11.0415,1.95
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,218.04,181.76,221.04,218.0,169.9150,29.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41,343.40,256.58,346.40,343.4,254.9915,45.00
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53,386.53,313.47,389.53,386.5,297.5000,52.50
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95,116.85,82.95,119.85,116.8,84.9150,14.98
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72,64.71,47.27,67.71,64.7,47.5915,8.40
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79,55.79,30.21,58.79,55.8,36.5500,6.45

# 5. Group by
> theo cột nào, giá trị nào, hàm nào

## 1 hàm cho 1 cột
## 1 hàm cho nhiều cột
## Nhiều hàm cho nhiều cột
## Nhiều hàm và chỉ định từng hàm cho từng giá trị

# Group by Challenge
1. Tính tổng doanh thu (price) cho từng sản phẩm (product_id).

2. Tính tổng doanh thu (price) theo cả product_id và seller_id.

3. Tính tổng và trung bình freight_value cho từng product_id.

4. Với mỗi người bán (seller_id), tính tổng price, trung bình freight_value, và đếm số đơn hàng (order_item_id).

In [82]:
# Tính tổng doanh thu (price) cho từng sản phẩm (product_id)
"""1 hàm cho 1 cột """
df_order_items.groupby('product_id')['price'].sum().reset_index()

                             product_id   price
0      00066f42aeeb9f3007548bb9d3f33c38  101.65
1      00088930e925c41fd95ebfe695fd2655  129.90
2      0009406fd7479715e4bef61dd91f2462  229.00
3      000b8f95fcb9e0096488278317764d19  117.80
4      000d9be29b5207b54e86aa1b1ac54872  199.00
...                                 ...     ...
32946  fff6177642830a9a94a0f2cba5e476d1  229.98
32947  fff81cc3158d2725c0655ab9ba0f712c   90.00
32948  fff9553ac224cec9d15d49f5a263411f   32.00
32949  fffdb2d0ec8d6a61f0a0a0db3f25b441  169.95
32950  fffe9eeff12fcbd74a2f2b007dde0c58  249.99

[32951 rows x 2 columns]

In [83]:
# Tính tổng doanh thu (price) theo cả product_id và seller_id.
"""1 hàm cho nhiều cột """
df_order_items.groupby(['product_id','seller_id'])['price'].sum().reset_index()

,product_id,seller_id,price
0,00066f42aeeb9f3007548bb9d3f33c38,5670f4db5b62c43d542e1b2d56b0cf7c,101.65
1,00088930e925c41fd95ebfe695fd2655,7142540dd4c91e2237acb7e911c4eba2,129.90
2,0009406fd7479715e4bef61dd91f2462,4a3ca9315b744ce9f8e9374361493884,229.00
3,000b8f95fcb9e0096488278317764d19,40ec8ab6cdafbcc4f544da38c67da39a,117.80
4,000d9be29b5207b54e86aa1b1ac54872,8ae520247981aa06bc94abddf5f46d34,199.00
...,...,...,...
34443,fff6177642830a9a94a0f2cba5e476d1,7a67c85e85bb2ce8582c35f2203ad736,229.98
34444,fff81cc3158d2725c0655ab9ba0f712c,778323240ce2830d68aab11794e00bfb,90.00
34445,fff9553ac224cec9d15d49f5a263411f,643214e62b870443ccbe55ab29a4dccf,32.00
34446,fffdb2d0ec8d6a61f0a0a0db3f25b441,9f505651f4a6abe901a56cdc21508025,169.95
34447,fffe9eeff12fcbd74a2f2b007dde0c58,7299e27ed73d2ad986de7f7c77d919fa,249.99

In [85]:
# Tính tổng và trung bình freight_value cho từng product_id.
"""Nhiều hàm cho nhiều (1) cột """
df_order_items.groupby('product_id').agg(total_freight_value=('freight_value','sum'),avg_freight_value=('freight_value','mean')).reset_index()

,product_id,total_freight_value,avg_freight_value
0,00066f42aeeb9f3007548bb9d3f33c38,18.59,18.590
1,00088930e925c41fd95ebfe695fd2655,13.93,13.930
2,0009406fd7479715e4bef61dd91f2462,13.10,13.100
3,000b8f95fcb9e0096488278317764d19,39.20,19.600
4,000d9be29b5207b54e86aa1b1ac54872,19.27,19.270
...,...,...,...
32946,fff6177642830a9a94a0f2cba5e476d1,55.41,27.705
32947,fff81cc3158d2725c0655ab9ba0f712c,7.89,7.890
32948,fff9553ac224cec9d15d49f5a263411f,11.85,11.850
32949,fffdb2d0ec8d6a61f0a0a0db3f25b441,58.87,11.774
32950,fffe9eeff12fcbd74a2f2b007dde0c58,53.88,53.880

In [88]:
#  Với mỗi người bán (seller_id), tính tổng price, trung bình freight_value, và đếm số đơn hàng (order_item_id).
"""Nhiều hàm và chỉ định từng hàm cho từng giá trị """
df_order_items.groupby('seller_id').agg( total_price = ('price','sum'),
                                        avg_freight_value = ('freight_value','mean'),
                                         count_orders = ('order_item_id','count')).reset_index()

,seller_id,total_price,avg_freight_value,count_orders
0,0015a82c2db000af6aaaf3ae2ecb0532,2685.00,21.020000,3
1,001cca7ae9ae17fb1caed9dfb1094831,25080.03,37.046611,239
2,001e6ad469a905060d959994f1b41e4f,250.00,17.940000,1
3,002100f778ceb8431b7a1020ff7ab48f,1234.50,14.430182,55
4,003554e2dce176b5555353e4f3555ac8,120.00,19.380000,1
...,...,...,...,...
3090,ffcfefa19b08742c5d315f2791395ee5,69.90,9.620000,1
3091,ffdd9f82b9a447f6f8d4b91554cc7dd3,2101.20,36.373000,20
3092,ffeee66ac5d5a62fe688b9d26f83f534,1839.86,29.977857,14
3093,fffd5413c0700ac820c7069d66d98c89,9062.30,46.454754,61
3094,ffff564a4f9085cd26170f4732393726,1426.30,17.228000,20