<a href="https://colab.research.google.com/github/Jenn2626/Python/blob/main/Pandas%20%26%20Pumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

scores =[85,95,78,64,89,95,73,88]
1. Tạo 1 pandas series từ danh sách scores
2. Lọc tất cả điểm >=90
3. Tăng tất cả điểm thêm 5 và tạo 1 series mới
4. Tính tổng điểm và điểm tb
5. Tìm điểm < hơn điểm tb

In [10]:
import pandas as pd
import numpy as np
scores =[85,95,78,64,89,95,73,88]
scores_series = pd.Series(scores)
scores_series
# Lọc tất cả điểm >=90
scores_series[scores_series >= 90]

1    95
5    95
dtype: int64

In [11]:
# Tăng tất cả điểm thêm 5 và tạo 1 series mới
new_scores_series = scores_series + 5
new_scores_series

0     90
1    100
2     83
3     69
4     94
5    100
6     78
7     93
dtype: int64

In [14]:
# Tính tổng điểm pandas
print('Tổng điểm:',new_scores_series.sum())
print('Tb điểm:',new_scores_series.mean())

Tổng điểm: 707
Tb điểm: 88.375

In [17]:
# Tính tổng điểm numpy
total = np.sum(new_scores_series)
mean = np.mean(new_scores_series)
print('Tổng điểm:',total)
print('Tb điểm:',mean)

Tổng điểm: 707
Tb điểm: 88.375

In [18]:
# Tìm điểm < hơn điểm tb
new_scores_series[new_scores_series < mean]

2    83
3    69
6    78
dtype: int64