<a href="https://colab.research.google.com/github/Jenn2626/Python/blob/main/PC4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#EX1: scores.csv
1.1 Sort and display teams in ascending order of score.

1.2 Sort and display teams in ascending order of category, then by score.

1.3 Calculate the mean of score for all teams.

1.4 Filter teams with score greater than 80 and display them in descending order of year.

1.5 Create a new column score_plus_10 by adding 10 to score.

1.6 Create a new column score_ratio as score / max(score).

1.7 Filter teams with category = ‘A’ or ‘B’ and score > 75.

1.8 Group by category and calculate the sum of score for each group.

In [4]:
# Read file
import pandas as pd
df_scores = pd.read_csv('/content/scores.csv')
df_scores.head()
df_scores.shape
df_scores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        1000 non-null   int64
 1   name      1000 non-null   object
 2   category  1000 non-null   object
 3   score     1000 non-null   int64
 4   year      1000 non-null   int64
dtypes: int64(3), object(2)
memory usage: 39.2+ KB

In [5]:
# Sort and display teams in ascending order of score
df_scores.sort_values('score', ascending=True)
df_scores

       id       name category  score  year
0       1     Name_1        D     92  2018
1       2     Name_2        A     86  2020
2       3     Name_3        B     85  2021
3       4     Name_4        C     58  2021
4       5     Name_5        C     90  2020
..    ...        ...      ...    ...   ...
995   996   Name_996        C     93  2021
996   997   Name_997        D     92  2020
997   998   Name_998        C     93  2021
998   999   Name_999        A     92  2019
999  1000  Name_1000        A     73  2020

[1000 rows x 5 columns]

In [6]:
# Sort and display teams in ascending order of category, then by score
df_scores.sort_values(['category','score'],ascending=[True,True])
df_scores

       id       name category  score  year
0       1     Name_1        D     92  2018
1       2     Name_2        A     86  2020
2       3     Name_3        B     85  2021
3       4     Name_4        C     58  2021
4       5     Name_5        C     90  2020
..    ...        ...      ...    ...   ...
995   996   Name_996        C     93  2021
996   997   Name_997        D     92  2020
997   998   Name_998        C     93  2021
998   999   Name_999        A     92  2019
999  1000  Name_1000        A     73  2020

[1000 rows x 5 columns]

In [7]:
#  Calculate the mean of score for all teams
import numpy as np
df_scores['mean_score'] = np.mean(df_scores['score'])
df_scores

       id       name category  score  year  mean_score
0       1     Name_1        D     92  2018      74.649
1       2     Name_2        A     86  2020      74.649
2       3     Name_3        B     85  2021      74.649
3       4     Name_4        C     58  2021      74.649
4       5     Name_5        C     90  2020      74.649
..    ...        ...      ...    ...   ...         ...
995   996   Name_996        C     93  2021      74.649
996   997   Name_997        D     92  2020      74.649
997   998   Name_998        C     93  2021      74.649
998   999   Name_999        A     92  2019      74.649
999  1000  Name_1000        A     73  2020      74.649

[1000 rows x 6 columns]

In [12]:
# Filter teams with score greater than 80 and display them in descending order of year.

df_scores[df_scores['score'] > 80].sort_values('year', ascending=False)

      id      name category  score  year  mean_score
997  998  Name_998        C     93  2021      74.649
2      3    Name_3        B     85  2021      74.649
10    11   Name_11        D     97  2021      74.649
7      8    Name_8        C    100  2021      74.649
21    22   Name_22        B     96  2021      74.649
..   ...       ...      ...    ...   ...         ...
936  937  Name_937        C     86  2018      74.649
938  939  Name_939        A     83  2018      74.649
937  938  Name_938        D     98  2018      74.649
949  950  Name_950        A     98  2018      74.649
0      1    Name_1        D     92  2018      74.649

[397 rows x 6 columns]

In [14]:
# Create a new column score_plus_10 by adding 10 to score.
df_scores['plus_score'] = df_scores['score'] + 10
df_scores

       id       name category  score  year  mean_score  plus_score
0       1     Name_1        D     92  2018      74.649         102
1       2     Name_2        A     86  2020      74.649          96
2       3     Name_3        B     85  2021      74.649          95
3       4     Name_4        C     58  2021      74.649          68
4       5     Name_5        C     90  2020      74.649         100
..    ...        ...      ...    ...   ...         ...         ...
995   996   Name_996        C     93  2021      74.649         103
996   997   Name_997        D     92  2020      74.649         102
997   998   Name_998        C     93  2021      74.649         103
998   999   Name_999        A     92  2019      74.649         102
999  1000  Name_1000        A     73  2020      74.649          83

[1000 rows x 7 columns]

In [15]:
# Create a new column score_ratio as score / max(score)
df_scores['score_ratio'] =  df_scores['score']/df_scores['score'].max()
df_scores

,id,name,category,score,year,mean_score,plus_score,score_ratio
0,1,Name_1,D,92,2018,74.649,102,0.92
1,2,Name_2,A,86,2020,74.649,96,0.86
2,3,Name_3,B,85,2021,74.649,95,0.85
3,4,Name_4,C,58,2021,74.649,68,0.58
4,5,Name_5,C,90,2020,74.649,100,0.90
...,...,...,...,...,...,...,...,...
995,996,Name_996,C,93,2021,74.649,103,0.93
996,997,Name_997,D,92,2020,74.649,102,0.92
997,998,Name_998,C,93,2021,74.649,103,0.93
998,999,Name_999,A,92,2019,74.649,102,0.92
999,1000,Name_1000,A,73,2020,74.649,83,0.73

In [17]:
# Filter teams with category = ‘A’ or ‘B’ and score > 75.
# df_scores['category'].isin(['A','B'])
# df_scores['score'] > 75
df_scores[(df_scores['category'].isin(['A','B'])) & (df_scores['score'] > 75)]

      id      name category  score  year  mean_score  plus_score  score_ratio
1      2    Name_2        A     86  2020      74.649          96         0.86
2      3    Name_3        B     85  2021      74.649          95         0.85
13    14   Name_14        A     92  2021      74.649         102         0.92
21    22   Name_22        B     96  2021      74.649         106         0.96
22    23   Name_23        B     79  2019      74.649          89         0.79
..   ...       ...      ...    ...   ...         ...         ...          ...
974  975  Name_975        A     94  2020      74.649         104         0.94
977  978  Name_978        A     85  2020      74.649          95         0.85
978  979  Name_979        A     96  2020      74.649         106         0.96
993  994  Name_994        A     89  2019      74.649          99         0.89
998  999  Name_999        A     92  2019      74.649         102         0.92

[234 rows x 8 columns]

In [19]:
# Group by category and calculate the sum of score for each group
df_scores.groupby('category')['score'].sum().reset_index()
df_scores

,id,name,category,score,year,mean_score,plus_score,score_ratio
0,1,Name_1,D,92,2018,74.649,102,0.92
1,2,Name_2,A,86,2020,74.649,96,0.86
2,3,Name_3,B,85,2021,74.649,95,0.85
3,4,Name_4,C,58,2021,74.649,68,0.58
4,5,Name_5,C,90,2020,74.649,100,0.90
...,...,...,...,...,...,...,...,...
995,996,Name_996,C,93,2021,74.649,103,0.93
996,997,Name_997,D,92,2020,74.649,102,0.92
997,998,Name_998,C,93,2021,74.649,103,0.93
998,999,Name_999,A,92,2019,74.649,102,0.92
999,1000,Name_1000,A,73,2020,74.649,83,0.73

# EX2: euro_12.csv
2.1 Filter 5 columns: Team, Goals, Yellow Cards, Red Cards, Players Used.

2.2 Sort teams in ascending order of Players Used.

2.3 Sort teams in ascending order of Yellow Cards and Red Cards.

2.4 Calculate the mean of Yellow Cards for all teams.

2.5 Filter teams with more than 9 Goals and sort them in descending order of Passes.

2.6 Create a new column Shooting Accuracy = (Shots on target / (Shots on target + Shots off target)) × 100.

2.7 Sort and display teams, Goals, and Shooting Accuracy in descending order of Shooting Accuracy.

In [20]:
# Read file
df_euro = pd.read_csv('/content/euro_12.csv')
df_euro.head()
df_euro.shape
df_euro.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Team               16 non-null     object
 1   Goals              16 non-null     int64
 2   Shots on target    16 non-null     int64
 3   Shots off target   16 non-null     int64
 4   Passes             16 non-null     int64
 5   Passes completed   16 non-null     int64
 6   Touches            16 non-null     int64
 7   Corners Taken      16 non-null     int64
 8   Tackles            16 non-null     int64
 9   Offsides           16 non-null     int64
 10  Yellow Cards       16 non-null     int64
 11  Red Cards          16 non-null     int64
 12  Players Used       16 non-null     int64
 13  Shooting Accuracy  16 non-null     float64
dtypes: float64(1), int64(12), object(1)
memory usage: 1.9+ KB

In [22]:
# Filter 5 columns: Team, Goals, Yellow Cards, Red Cards, Players Used.
df_euro[['Team','Goals','Yellow Cards','Red Cards','Players Used']].reset_index()

    index                 Team  Goals  Yellow Cards  Red Cards  Players Used
0       0              Croatia      4             9          0            16
1       1       Czech Republic      4             7          0            19
2       2              Denmark      4             4          0            15
3       3              England      5             5          0            16
4       4               France      3             6          0            19
5       5              Germany     10             4          0            17
6       6               Greece      5             9          1            20
7       7                Italy      6            16          0            19
8       8          Netherlands      2             5          0            15
9       9               Poland      2             7          1            17
10     10             Portugal      6            12          0            16
11     11  Republic of Ireland      1             6          1            17
12     12               Russia      5             6          0            16
13     13                Spain     12            11          0            18
14     14               Sweden      5             7          0            18
15     15              Ukraine      2             5          0            18

In [27]:
# Sort teams in ascending order of Players Used.
sort_df = df_euro.sort_values('Players Used', ascending=True).reset_index()
sort_df

,index,Team,Goals,Shots on target,Shots off target,Passes,Passes completed,Touches,Corners Taken,Tackles,Offsides,Yellow Cards,Red Cards,Players Used,Shooting Accuracy
0,2,Denmark,4,10,10,1298,1082,1873,16,40,8,4,0,15,50.00
1,8,Netherlands,2,12,36,1556,1381,2163,22,34,3,5,0,15,25.00
2,3,England,5,11,18,1488,1200,2440,16,86,6,5,0,16,37.93
3,0,Croatia,4,13,12,1076,828,1706,14,49,2,9,0,16,52.00
4,10,Portugal,6,22,42,1891,1461,2958,41,78,10,12,0,16,34.38
5,12,Russia,5,9,31,1602,1345,2278,21,65,4,6,0,16,22.50
6,9,Poland,2,15,23,1059,852,1724,14,67,3,7,1,17,39.47
7,5,Germany,10,32,32,2774,2427,3761,35,91,12,4,0,17,50.00
8,11,Republic of Ireland,1,7,12,851,606,1433,8,45,11,6,1,17,36.84
9,13,Spain,12,42,33,4317,3820,5585,44,122,19,11,0,18,56.00
10,14,Sweden,5,17,19,1192,965,1806,7,56,7,7,0,18,47.22
11,15,Ukraine,2,7,26,1276,1043,1894,18,65,4,5,0,18,21.21
12,4,France,3,22,24,2066,1803,2909,28,71,5,6,0,19,47.83
13,7,Italy,6,34,45,3016,2531,4363,30,98,16,16,0,19,43.04
14,1,Czech Republic,4,13,18,1565,1223,2358,21,62,8,7,0,19,41.94
15,6,Greece,5,8,18,1187,911,2016,10,65,12,9,1,20,30.77

In [35]:
#  Sort teams in ascending order of Yellow Cards and Red Cards.
sort_card = df_euro.sort_values(['Yellow Cards','Red Cards'], ascending=[True,True]).reset_index()
sort_card

,index,Team,Goals,Shots on target,Shots off target,Passes,Passes completed,Touches,Corners Taken,Tackles,Offsides,Yellow Cards,Red Cards,Players Used,Shooting Accuracy
0,2,Denmark,4,10,10,1298,1082,1873,16,40,8,4,0,15,50.00
1,5,Germany,10,32,32,2774,2427,3761,35,91,12,4,0,17,50.00
2,3,England,5,11,18,1488,1200,2440,16,86,6,5,0,16,37.93
3,8,Netherlands,2,12,36,1556,1381,2163,22,34,3,5,0,15,25.00
4,15,Ukraine,2,7,26,1276,1043,1894,18,65,4,5,0,18,21.21
5,4,France,3,22,24,2066,1803,2909,28,71,5,6,0,19,47.83
6,12,Russia,5,9,31,1602,1345,2278,21,65,4,6,0,16,22.50
7,11,Republic of Ireland,1,7,12,851,606,1433,8,45,11,6,1,17,36.84
8,1,Czech Republic,4,13,18,1565,1223,2358,21,62,8,7,0,19,41.94
9,14,Sweden,5,17,19,1192,965,1806,7,56,7,7,0,18,47.22
10,9,Poland,2,15,23,1059,852,1724,14,67,3,7,1,17,39.47
11,0,Croatia,4,13,12,1076,828,1706,14,49,2,9,0,16,52.00
12,6,Greece,5,8,18,1187,911,2016,10,65,12,9,1,20,30.77
13,13,Spain,12,42,33,4317,3820,5585,44,122,19,11,0,18,56.00
14,10,Portugal,6,22,42,1891,1461,2958,41,78,10,12,0,16,34.38
15,7,Italy,6,34,45,3016,2531,4363,30,98,16,16,0,19,43.04

In [38]:
# Calculate the mean of Yellow Cards for all teams
import numpy as np
df_euro['mean_yellow'] = np.round((df_euro['Yellow Cards']).mean(),2)
df_euro

,Team,Goals,Shots on target,Shots off target,Passes,Passes completed,Touches,Corners Taken,Tackles,Offsides,Yellow Cards,Red Cards,Players Used,Shooting Accuracy,mean_yellow
0,Croatia,4,13,12,1076,828,1706,14,49,2,9,0,16,52.00,7.44
1,Czech Republic,4,13,18,1565,1223,2358,21,62,8,7,0,19,41.94,7.44
2,Denmark,4,10,10,1298,1082,1873,16,40,8,4,0,15,50.00,7.44
3,England,5,11,18,1488,1200,2440,16,86,6,5,0,16,37.93,7.44
4,France,3,22,24,2066,1803,2909,28,71,5,6,0,19,47.83,7.44
5,Germany,10,32,32,2774,2427,3761,35,91,12,4,0,17,50.00,7.44
6,Greece,5,8,18,1187,911,2016,10,65,12,9,1,20,30.77,7.44
7,Italy,6,34,45,3016,2531,4363,30,98,16,16,0,19,43.04,7.44
8,Netherlands,2,12,36,1556,1381,2163,22,34,3,5,0,15,25.00,7.44
9,Poland,2,15,23,1059,852,1724,14,67,3,7,1,17,39.47,7.44
10,Portugal,6,22,42,1891,1461,2958,41,78,10,12,0,16,34.38,7.44
11,Republic of Ireland,1,7,12,851,606,1433,8,45,11,6,1,17,36.84,7.44
12,Russia,5,9,31,1602,1345,2278,21,65,4,6,0,16,22.50,7.44
13,Spain,12,42,33,4317,3820,5585,44,122,19,11,0,18,56.00,7.44
14,Sweden,5,17,19,1192,965,1806,7,56,7,7,0,18,47.22,7.44
15,Ukraine,2,7,26,1276,1043,1894,18,65,4,5,0,18,21.21,7.44

In [40]:
# Filter teams with more than 9 Goals and sort them in descending order of Passes.
df_euro[df_euro['Goals'] > 9].sort_values('Passes', ascending=False)

,Team,Goals,Shots on target,Shots off target,Passes,Passes completed,Touches,Corners Taken,Tackles,Offsides,Yellow Cards,Red Cards,Players Used,Shooting Accuracy,mean_yellow
13,Spain,12,42,33,4317,3820,5585,44,122,19,11,0,18,56.0,7.44
5,Germany,10,32,32,2774,2427,3761,35,91,12,4,0,17,50.0,7.44

In [43]:
# Create a new column Shooting Accuracy = (Shots on target / (Shots on target + Shots off target)) × 100.
import numpy as np

df_euro['Shooting Accuracy'] = np.round(df_euro['Shots on target']/ (df_euro['Shots on target'] + df_euro['Shots off target'])*100,2)

df_euro

,Team,Goals,Shots on target,Shots off target,Passes,Passes completed,Touches,Corners Taken,Tackles,Offsides,Yellow Cards,Red Cards,Players Used,Shooting Accuracy,mean_yellow
0,Croatia,4,13,12,1076,828,1706,14,49,2,9,0,16,52.00,7.44
1,Czech Republic,4,13,18,1565,1223,2358,21,62,8,7,0,19,41.94,7.44
2,Denmark,4,10,10,1298,1082,1873,16,40,8,4,0,15,50.00,7.44
3,England,5,11,18,1488,1200,2440,16,86,6,5,0,16,37.93,7.44
4,France,3,22,24,2066,1803,2909,28,71,5,6,0,19,47.83,7.44
5,Germany,10,32,32,2774,2427,3761,35,91,12,4,0,17,50.00,7.44
6,Greece,5,8,18,1187,911,2016,10,65,12,9,1,20,30.77,7.44
7,Italy,6,34,45,3016,2531,4363,30,98,16,16,0,19,43.04,7.44
8,Netherlands,2,12,36,1556,1381,2163,22,34,3,5,0,15,25.00,7.44
9,Poland,2,15,23,1059,852,1724,14,67,3,7,1,17,39.47,7.44
10,Portugal,6,22,42,1891,1461,2958,41,78,10,12,0,16,34.38,7.44
11,Republic of Ireland,1,7,12,851,606,1433,8,45,11,6,1,17,36.84,7.44
12,Russia,5,9,31,1602,1345,2278,21,65,4,6,0,16,22.50,7.44
13,Spain,12,42,33,4317,3820,5585,44,122,19,11,0,18,56.00,7.44
14,Sweden,5,17,19,1192,965,1806,7,56,7,7,0,18,47.22,7.44
15,Ukraine,2,7,26,1276,1043,1894,18,65,4,5,0,18,21.21,7.44

In [46]:
# Sort and display teams, Goals, and Shooting Accuracy in descending order of Shooting Accuracy.

df_euro.sort_values(['Team', 'Goals', 'Shooting Accuracy'], ascending=[False,False,False])
df_euro

,Team,Goals,Shots on target,Shots off target,Passes,Passes completed,Touches,Corners Taken,Tackles,Offsides,Yellow Cards,Red Cards,Players Used,Shooting Accuracy,mean_yellow
0,Croatia,4,13,12,1076,828,1706,14,49,2,9,0,16,52.00,7.44
1,Czech Republic,4,13,18,1565,1223,2358,21,62,8,7,0,19,41.94,7.44
2,Denmark,4,10,10,1298,1082,1873,16,40,8,4,0,15,50.00,7.44
3,England,5,11,18,1488,1200,2440,16,86,6,5,0,16,37.93,7.44
4,France,3,22,24,2066,1803,2909,28,71,5,6,0,19,47.83,7.44
5,Germany,10,32,32,2774,2427,3761,35,91,12,4,0,17,50.00,7.44
6,Greece,5,8,18,1187,911,2016,10,65,12,9,1,20,30.77,7.44
7,Italy,6,34,45,3016,2531,4363,30,98,16,16,0,19,43.04,7.44
8,Netherlands,2,12,36,1556,1381,2163,22,34,3,5,0,15,25.00,7.44
9,Poland,2,15,23,1059,852,1724,14,67,3,7,1,17,39.47,7.44
10,Portugal,6,22,42,1891,1461,2958,41,78,10,12,0,16,34.38,7.44
11,Republic of Ireland,1,7,12,851,606,1433,8,45,11,6,1,17,36.84,7.44
12,Russia,5,9,31,1602,1345,2278,21,65,4,6,0,16,22.50,7.44
13,Spain,12,42,33,4317,3820,5585,44,122,19,11,0,18,56.00,7.44
14,Sweden,5,17,19,1192,965,1806,7,56,7,7,0,18,47.22,7.44
15,Ukraine,2,7,26,1276,1043,1894,18,65,4,5,0,18,21.21,7.44

# EX3: users.txt
3.1 Calculate the mean age for each occupation.

3.2 Calculate the male ratio (%) for each occupation.

3.3 Sort male ratios in descending order.

3.4 Find and display min and max ages for each occupation.

3.5 Calculate and display mean ages of male and female for each occupation.

3.6 Count and display occupations by gender (male and female).

In [49]:
# Create file
df_users = pd.read_csv('/content/users.txt', sep='|')
df_users.head()
df_users.shape
df_users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 943 entries, 0 to 942
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   user_id     943 non-null    int64
 1   age         943 non-null    int64
 2   gender      943 non-null    object
 3   occupation  943 non-null    object
 4   zip_code    943 non-null    object
dtypes: int64(2), object(3)
memory usage: 37.0+ KB

In [52]:
# Calculate the mean age for each occupation.
import numpy as np
df_users.groupby('occupation')['age'].mean().round(2).reset_index()

       occupation    age
0   administrator  38.75
1          artist  31.39
2          doctor  43.57
3        educator  42.01
4        engineer  36.39
5   entertainment  29.22
6       executive  38.72
7      healthcare  41.56
8       homemaker  32.57
9          lawyer  36.75
10      librarian  40.00
11      marketing  37.62
12           none  26.56
13          other  34.52
14     programmer  33.12
15        retired  63.07
16       salesman  35.67
17      scientist  35.55
18        student  22.08
19     technician  33.15
20         writer  36.31

In [57]:
# Calculate the male ratio (%) for each occupation.
import numpy as np

# Count total users per occupation
total_user = df_users.groupby("occupation")["gender"].count()

# Count male users per occupation
male_user = df_users[df_users["gender"] == "M"].groupby("occupation")["gender"].count()

# Calculate male ratio (%)
male_ratio = (male_user / total_user * 100).round(2).reset_index(name="male_ratio_percent")

male_ratio

       occupation  male_ratio_percent
0   administrator               54.43
1          artist               53.57
2          doctor              100.00
3        educator               72.63
4        engineer               97.01
5   entertainment               88.89
6       executive               90.62
7      healthcare               31.25
8       homemaker               14.29
9          lawyer               83.33
10      librarian               43.14
11      marketing               61.54
12           none               55.56
13          other               65.71
14     programmer               90.91
15        retired               92.86
16       salesman               75.00
17      scientist               90.32
18        student               69.39
19     technician               96.30
20         writer               57.78