<a href="https://colab.research.google.com/github/Jenn2626/Python/blob/main/PC6_Clean_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Read data from the messy_data.xlsx file and perform the following tasks:

1. List the issues you notice in the dataset
Hint: Look for missing data, inconsistent formats, special characters, or incorrect data types.
2. Remove non-alphabetic characters from First_Name and Last_Name
Example: If the name is /Alex.1, it should be converted to Alex.
Hint: Use string methods like .str.replace() or regular expressions (regex) to remove unwanted characters.
3. Format phone numbers to the format nnn-nnn-nnnn
Hint:
+ For rows containing any non-numeric characters (such as letters), replace them with an empty string.
+ After cleaning the phone numbers, format them in the style nnn-nnn-nnnn (e.g., 123-178-3720)

4. Create new columns Street_Address, State, and Zip_Code from the existing Street_Address column
Example: 980 Paper Avenue, Pennsylvania, 18503 should be split as:
+ Street_Address = ‘980 Paper Avenue’
+ Zip_Code = 18503
+ State = ‘Pennsylvania’. If any part is missing, assign None.
Hint: Use .str.extract() with regex or .str.split() to separate the address into components.

5. Standardize the Do_Not_Contact column to only have two values: Y or N
Hint: You can use .map() or .replace() to convert any variations (e.g., yes, no, y, n) to a consistent format.

6. Replace all NaN values with Unknown
Hint: Use .fillna() to replace missing values in the entire DataFrame.

In [53]:
# Read data
import pandas as pd
df_data = pd.read_excel('/content/messy_data.xlsx')

In [5]:
df_data.info()
df_data.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         21 non-null     int64
 1   First_Name         21 non-null     object
 2   Last_Name          20 non-null     object
 3   Phone_Number       19 non-null     object
 4   Address            21 non-null     object
 5   Paying Customer    21 non-null     object
 6   Do_Not_Contact     17 non-null     object
 7   Not_Useful_Column  21 non-null     bool
dtypes: bool(1), int64(1), object(6)
memory usage: 1.3+ KB

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True

In [56]:
# Remove non-alphabetic characters from First_Name and Last_Name
# Find which row include that condition
pattern = r'[^a-zA-Z\s]'
df_data[df_data['First_Name'].str.contains(pattern, na=False, regex=True)]
df_data[df_data['Last_Name'].str.contains(pattern, na=False, regex=True)]

# Remove non-alphabetic: any character matching the pattern will be replaced with an empty string
df_data['First_Name'] = df_data['First_Name'].str.replace(pattern,'', regex = True)
df_data['Last_Name'] = df_data['Last_Name'].str.replace(pattern,'', regex = True)

In [55]:
# Recheck
pattern = r'[^a-zA-Z\s]'
df_data[df_data['First_Name'].str.contains(pattern, na=False, regex=True)]
df_data[df_data['Last_Name'].str.contains(pattern, na=False, regex=True)]

Empty DataFrame
Columns: [CustomerID, First_Name, Last_Name, Phone_Number, Address, Paying Customer, Do_Not_Contact, Not_Useful_Column]
Index: []

In [57]:
# Format phone numbers to the format nnn-nnn-nnnn Hint:
# For rows containing any non-numeric characters (such as letters), replace them with an empty string.

# Find phone number is non numeric
pattern = r'[^\d]'
df_data[df_data['Phone_Number'].str.contains(pattern, na=False, regex=True)]

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [58]:
# Replace non-numeric with empty string
df_data['Phone_Number'] = df_data['Phone_Number'].str.replace(pattern,'', regex = True)
df_data['Phone_Number']

0     1235455421
1     1236439775
2            NaN
3     1235432345
4     8766783469
5     3047622467
6            NaN
7     8766783469
8
9     1235455421
10           NaN
11           NaN
12    1235432345
13    8766783469
14    3047622467
15    1235455421
16    1236439775
17           NaN
18
19    8766783469
20    8766783469
Name: Phone_Number, dtype: object

In [59]:
# Format them in the style nnn-nnn-nnnn (e.g., 123-178-3720)
pattern_1 = r'(\d{3})(\d{3})(\d{4})'
pattern_2 = r'\1-\2-\3'
df_data['Phone_Number'] = df_data['Phone_Number'].str.replace(pattern_1, pattern_2, regex=True)
df_data['Phone_Number']

0     123-545-5421
1     123-643-9775
2              NaN
3     123-543-2345
4     876-678-3469
5     304-762-2467
6              NaN
7     876-678-3469
8
9     123-545-5421
10             NaN
11             NaN
12    123-543-2345
13    876-678-3469
14    304-762-2467
15    123-545-5421
16    123-643-9775
17             NaN
18
19    876-678-3469
20    876-678-3469
Name: Phone_Number, dtype: object

In [60]:
"""" Create new columns Street_Address, State, and Zip_Code from the existing Street_Address column
Example: 980 Paper Avenue, Pennsylvania, 18503 should be split as:
Street_Address = ‘980 Paper Avenue’
Zip_Code = 18503
State = ‘Pennsylvania’.
If any part is missing, assign None. Hint: Use .str.extract() with regex or .str.split() to separate the address into components."""
df_data.head(5)

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,False
2,1003,Walter,White,NaN,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,True

In [63]:
# Split Address
df_data['New_Address'] = df_data['Address'].str.split(',')
df_data.head(5)

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,New_Address
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True,"[123 Shire Lane, Shire]"
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,False,[93 West Main Street]
2,1003,Walter,White,NaN,298 Drugs Driveway,N,NaN,True,[298 Drugs Driveway]
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,"[980 Paper Avenue, Pennsylvania, 18503]"
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,True,[123 Dragons Road]

In [64]:

df_data['Street_Address'] = df_data['New_Address'].str[0]
df_data['State'] = df_data['New_Address'].str[1]
df_data['Zip_Code'] = df_data['New_Address'].str[2]
df_data.head(5)

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,New_Address,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True,"[123 Shire Lane, Shire]",123 Shire Lane,Shire,NaN
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,False,[93 West Main Street],93 West Main Street,NaN,NaN
2,1003,Walter,White,NaN,298 Drugs Driveway,N,NaN,True,[298 Drugs Driveway],298 Drugs Driveway,NaN,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,"[980 Paper Avenue, Pennsylvania, 18503]",980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,True,[123 Dragons Road],123 Dragons Road,NaN,NaN

In [65]:
#   Missing data replace by None
df_data['Street_Address'] = df_data['Street_Address'].fillna('None')
df_data['State'] = df_data['State'].fillna('None')
df_data['Zip_Code'] = df_data['Zip_Code'].fillna('None')
df_data.head(5)

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,New_Address,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True,"[123 Shire Lane, Shire]",123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,False,[93 West Main Street],93 West Main Street,None,None
2,1003,Walter,White,NaN,298 Drugs Driveway,N,NaN,True,[298 Drugs Driveway],298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,"[980 Paper Avenue, Pennsylvania, 18503]",980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,True,[123 Dragons Road],123 Dragons Road,None,None

In [67]:
"""Standardize the Do_Not_Contact column to only have two values: Y or N
Hint: You can use .map() or .replace() to convert any variations (e.g., yes, no, y, n) to a consistent format."""
df_data.head(5)
df_data.tail(5)

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,New_Address,Street_Address,State,Zip_Code
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,False,"[121 Paper Avenue, Pennsylvania]",121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,NaN,3498 Super Lane,Y,NaN,True,[3498 Super Lane],3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,N/a,Yes,True,[N/a],N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,True,"[910 Tatooine Road, Tatooine]",910 Tatooine Road,Tatooine,None
20,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,True,"[910 Tatooine Road, Tatooine]",910 Tatooine Road,Tatooine,None

In [69]:
# Lower letter
df_data['Do_Not_Contact'] = df_data['Do_Not_Contact'].str.lower()
df_data.head(5)

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,New_Address,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,no,True,"[123 Shire Lane, Shire]",123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,yes,False,[93 West Main Street],93 West Main Street,None,None
2,1003,Walter,White,NaN,298 Drugs Driveway,N,NaN,True,[298 Drugs Driveway],298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,y,True,"[980 Paper Avenue, Pennsylvania, 18503]",980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,no,True,[123 Dragons Road],123 Dragons Road,None,None

In [70]:
# Standardize the Do_Not_Contact column to only have two values: Y or N  BY replace
df_data['Do_Not_Contact'] = df_data['Do_Not_Contact'].replace(['yes','no','y','n'],['Y','N','Y','N'])
df_data.head(5)

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,New_Address,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,N,True,"[123 Shire Lane, Shire]",123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Y,False,[93 West Main Street],93 West Main Street,None,None
2,1003,Walter,White,NaN,298 Drugs Driveway,N,NaN,True,[298 Drugs Driveway],298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,"[980 Paper Avenue, Pennsylvania, 18503]",980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,True,[123 Dragons Road],123 Dragons Road,None,None

In [72]:
# Replace all NaN values with Unknown Hint: Use .fillna() to replace missing values in the entire DataFrame
# Find missing vallue

def find_missing_value(df):
  missing_data = df_data.isnull().sum().to_frame('count_null')
  missing_data['percent_null'] = missing_data['count_null']/len(missing_data)
  return missing_data
find_missing_value(df_data)

                   count_null  percent_null
CustomerID                  0      0.000000
First_Name                  0      0.000000
Last_Name                   1      0.076923
Phone_Number                5      0.384615
Address                     0      0.000000
Paying Customer             0      0.000000
Do_Not_Contact              4      0.307692
Not_Useful_Column           0      0.000000
New_Address                 0      0.000000
Street_Address              0      0.000000
State                       0      0.000000
Zip_Code                    0      0.000000
Do_Not_Contac               0      0.000000

In [73]:
# Replace all NaN values with Unknown
df_data = df_data.fillna('Unknown')
df_data

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,New_Address,Street_Address,State,Zip_Code,Do_Not_Contac
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,N,True,"[123 Shire Lane, Shire]",123 Shire Lane,Shire,None,N
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Y,False,[93 West Main Street],93 West Main Street,None,None,Y
2,1003,Walter,White,Unknown,298 Drugs Driveway,N,Unknown,True,[298 Drugs Driveway],298 Drugs Driveway,None,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,"[980 Paper Avenue, Pennsylvania, 18503]",980 Paper Avenue,Pennsylvania,18503,Y
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,True,[123 Dragons Road],123 Dragons Road,None,None,N
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Y,True,[768 City Parkway],768 City Parkway,None,None,Y
6,1007,Jeff,Winger,Unknown,1209 South Street,No,N,False,[1209 South Street],1209 South Street,None,None,N
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,False,[98 Clue Drive],98 Clue Drive,None,None,N
8,1009,Gandalf,Unknown,,123 Middle Earth,Yes,Unknown,False,[123 Middle Earth],123 Middle Earth,None,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,N,True,"[25th Main Street, New York]",25th Main Street,New York,None,N
10,1011,Samwise,Gamgee,Unknown,"612 Shire Lane, Shire",Yes,N,True,"[612 Shire Lane, Shire]",612 Shire Lane,Shire,None,N
11,1012,Harry,Potter,Unknown,2394 Hogwarts Avenue,Y,Unknown,True,[2394 Hogwarts Avenue],2394 Hogwarts Avenue,None,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False,[2039 Main Street],2039 Main Street,None,None,N
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,N,False,[343 City Parkway],343 City Parkway,None,None,N
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,False,[214 HR Avenue],214 HR Avenue,None,None,N
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,[2395 Hogwarts Avenue],2395 Hogwarts Avenue,None,None,N
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,N,False,"[121 Paper Avenue, Pennsylvania]",121 Paper Avenue,Pennsylvania,None,N
17,1018,Clark,Kent,Unknown,3498 Super Lane,Y,Unknown,True,[3498 Super Lane],3498 Super Lane,None,None,None
18,1019,Creed,Braton,,N/a,N/a,Y,True,[N/a],N/a,None,None,Y
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,True,"[910 Tatooine Road, Tatooine]",910 Tatooine Road,Tatooine,None,N
20,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,True,"[910 Tatooine Road, Tatooine]",910 Tatooine Road,Tatooine,None,N

In [75]:
find_missing_value(df_data)

                   count_null  percent_null
CustomerID                  0           0.0
First_Name                  0           0.0
Last_Name                   0           0.0
Phone_Number                0           0.0
Address                     0           0.0
Paying Customer             0           0.0
Do_Not_Contact              0           0.0
Not_Useful_Column           0           0.0
New_Address                 0           0.0
Street_Address              0           0.0
State                       0           0.0
Zip_Code                    0           0.0
Do_Not_Contac               0           0.0