<a href="https://colab.research.google.com/github/Jenn2626/Python/blob/main/String_%26_Datetime.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [41]:
import pandas as pd
df_sales_data = pd.read_csv('/content/sales_dataset.csv')

In [42]:
df_sales_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   CustomerID  1025 non-null   int64
 1   JoinDate    1025 non-null   object
 2   Unused      0 non-null      float64
 3   Mobile      1025 non-null   float64
 4   Name        923 non-null    object
 5   Email       929 non-null    object
 6   Product     1025 non-null   object
 7   Scores      898 non-null    float64
 8   Birthdate   1025 non-null   object
 9   Revenue     1025 non-null   object
 10  Order_Date  1025 non-null   object
dtypes: float64(3), int64(1), object(7)
memory usage: 88.2+ KB

In [43]:
df_sales_data

,CustomerID,JoinDate,Unused,Mobile,Name,Email,Product,Scores,Birthdate,Revenue,Order_Date
0,1,8/7/19,NaN,8.433361e+10,mIChAel mIcHALek,contact812@domain.com,Tablet,66.0,2/10/97,7877$,9/7/23
1,2,9/10/18,NaN,9.734441e+08,Andrew Jimenez,service45@example.com,table,53.0,8/23/71,6087$,1/9/23
2,3,20190630,NaN,3.382630e+08,Ann Gow,service699@test.com,SMARTPHONE,77.0,11/5/83,1105$,8/7/23
3,4,2019-09-06 00:00:1567702800,NaN,8.496607e+10,James Chen,customer575@example.com,table,58.0,12/21/98,1019$,7/27/23
4,5,20170812,NaN,8.476707e+10,Dollie Martinez,admin235@domain.com,Smartphone,NaN,8/25/05,2985$,10/5/23
...,...,...,...,...,...,...,...,...,...,...,...
1020,1021,8/15/21,NaN,8.496412e+10,RubEN rAy,info613@test.com,tablet,54.0,12/29/77,8924$,4/8/23
1021,1022,6/8/21,NaN,8.435878e+10,tImoTHy wiLEY,admin191@example.com,Smartphone,84.0,2/2/74,1815$,2/14/23
1022,1023,7/2/22,NaN,8.476342e+10,ValaRiE EchoLS,service442@test.com,tablet,81.0,1/18/73,2148$,10/6/23
1023,1024,7/24/19,NaN,8.412880e+11,MArtA WOng,NaN,Smartphone,59.0,7/15/62,5127$,9/28/23
1024,1025,10/6/22,NaN,8.433743e+10,denNis rePiNE,contact528@domain.com,tablet,76.0,11/16/72,4006$,8/31/23

In [45]:
 # Spit datatype timestamp
 df_sales_data['JoinDate'] = df_sales_data['JoinDate'].str.split().str[0]
 df_sales_data

,CustomerID,JoinDate,Unused,Mobile,Name,Email,Product,Scores,Birthdate,Revenue,Order_Date
0,1,8/7/19,NaN,8.433361e+10,mIChAel mIcHALek,contact812@domain.com,Tablet,66.0,2/10/97,7877$,9/7/23
1,2,9/10/18,NaN,9.734441e+08,Andrew Jimenez,service45@example.com,table,53.0,8/23/71,6087$,1/9/23
2,3,20190630,NaN,3.382630e+08,Ann Gow,service699@test.com,SMARTPHONE,77.0,11/5/83,1105$,8/7/23
3,4,2019-09-06,NaN,8.496607e+10,James Chen,customer575@example.com,table,58.0,12/21/98,1019$,7/27/23
4,5,20170812,NaN,8.476707e+10,Dollie Martinez,admin235@domain.com,Smartphone,NaN,8/25/05,2985$,10/5/23
...,...,...,...,...,...,...,...,...,...,...,...
1020,1021,8/15/21,NaN,8.496412e+10,RubEN rAy,info613@test.com,tablet,54.0,12/29/77,8924$,4/8/23
1021,1022,6/8/21,NaN,8.435878e+10,tImoTHy wiLEY,admin191@example.com,Smartphone,84.0,2/2/74,1815$,2/14/23
1022,1023,7/2/22,NaN,8.476342e+10,ValaRiE EchoLS,service442@test.com,tablet,81.0,1/18/73,2148$,10/6/23
1023,1024,7/24/19,NaN,8.412880e+11,MArtA WOng,NaN,Smartphone,59.0,7/15/62,5127$,9/28/23
1024,1025,10/6/22,NaN,8.433743e+10,denNis rePiNE,contact528@domain.com,tablet,76.0,11/16/72,4006$,8/31/23

In [46]:
# Convert to datetime
data_col = ['JoinDate','Birthdate','Order_Date']
for col in data_col:
  df_sales_data[col] = pd.to_datetime(df_sales_data[col])

/tmp/ipykernel_19102/285812952.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_sales_data[col] = pd.to_datetime(df_sales_data[col])
/tmp/ipykernel_19102/285812952.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_sales_data[col] = pd.to_datetime(df_sales_data[col])
/tmp/ipykernel_19102/285812952.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_sales_data[col] = pd.to_datetime(df_sales_data[col])

In [47]:
df_sales_data

,CustomerID,JoinDate,Unused,Mobile,Name,Email,Product,Scores,Birthdate,Revenue,Order_Date
0,1,2019-08-07,NaN,8.433361e+10,mIChAel mIcHALek,contact812@domain.com,Tablet,66.0,1997-02-10,7877$,2023-09-07
1,2,2018-09-10,NaN,9.734441e+08,Andrew Jimenez,service45@example.com,table,53.0,2071-08-23,6087$,2023-01-09
2,3,2019-06-30,NaN,3.382630e+08,Ann Gow,service699@test.com,SMARTPHONE,77.0,1983-11-05,1105$,2023-08-07
3,4,2019-09-06,NaN,8.496607e+10,James Chen,customer575@example.com,table,58.0,1998-12-21,1019$,2023-07-27
4,5,2017-08-12,NaN,8.476707e+10,Dollie Martinez,admin235@domain.com,Smartphone,NaN,2005-08-25,2985$,2023-10-05
...,...,...,...,...,...,...,...,...,...,...,...
1020,1021,2021-08-15,NaN,8.496412e+10,RubEN rAy,info613@test.com,tablet,54.0,1977-12-29,8924$,2023-04-08
1021,1022,2021-06-08,NaN,8.435878e+10,tImoTHy wiLEY,admin191@example.com,Smartphone,84.0,2074-02-02,1815$,2023-02-14
1022,1023,2022-07-02,NaN,8.476342e+10,ValaRiE EchoLS,service442@test.com,tablet,81.0,2073-01-18,2148$,2023-10-06
1023,1024,2019-07-24,NaN,8.412880e+11,MArtA WOng,NaN,Smartphone,59.0,2062-07-15,5127$,2023-09-28
1024,1025,2022-10-06,NaN,8.433743e+10,denNis rePiNE,contact528@domain.com,tablet,76.0,2072-11-16,4006$,2023-08-31

In [59]:
diff = df_sales_data['Order_Date'] - df_sales_data['JoinDate']
df_sales_data['diff_day'] = diff.dt.days
df_sales_data

,CustomerID,JoinDate,Unused,Mobile,Name,Email,Product,Scores,Birthdate,Revenue,Order_Date,diff,diff_day
0,1,2019-08-07,NaN,8.433361e+10,mIChAel mIcHALek,contact812@domain.com,Tablet,66.0,1997-02-10,7877$,2023-09-07,49.733333,1492
1,2,2018-09-10,NaN,9.734441e+08,Andrew Jimenez,service45@example.com,table,53.0,2071-08-23,6087$,2023-01-09,52.733333,1582
2,3,2019-06-30,NaN,3.382630e+08,Ann Gow,service699@test.com,SMARTPHONE,77.0,1983-11-05,1105$,2023-08-07,49.966667,1499
3,4,2019-09-06,NaN,8.496607e+10,James Chen,customer575@example.com,table,58.0,1998-12-21,1019$,2023-07-27,47.333333,1420
4,5,2017-08-12,NaN,8.476707e+10,Dollie Martinez,admin235@domain.com,Smartphone,NaN,2005-08-25,2985$,2023-10-05,74.833333,2245
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,1021,2021-08-15,NaN,8.496412e+10,RubEN rAy,info613@test.com,tablet,54.0,1977-12-29,8924$,2023-04-08,20.033333,601
1021,1022,2021-06-08,NaN,8.435878e+10,tImoTHy wiLEY,admin191@example.com,Smartphone,84.0,2074-02-02,1815$,2023-02-14,20.533333,616
1022,1023,2022-07-02,NaN,8.476342e+10,ValaRiE EchoLS,service442@test.com,tablet,81.0,2073-01-18,2148$,2023-10-06,15.366667,461
1023,1024,2019-07-24,NaN,8.412880e+11,MArtA WOng,NaN,Smartphone,59.0,2062-07-15,5127$,2023-09-28,50.900000,1527
1024,1025,2022-10-06,NaN,8.433743e+10,denNis rePiNE,contact528@domain.com,tablet,76.0,2072-11-16,4006$,2023-08-31,10.966667,329

In [63]:
df_groupped = df_sales_data.groupby('Order_Date').agg(count_customer =('CustomerID','count')).reset_index()
df_groupped

    Order_Date  count_customer
0   2023-01-01               1
1   2023-01-02               4
2   2023-01-03               3
3   2023-01-04               1
4   2023-01-05               3
..         ...             ...
340 2023-12-27               3
341 2023-12-28               3
342 2023-12-29               2
343 2023-12-30               2
344 2023-12-31               2

[345 rows x 2 columns]

In [67]:
# Calculate previous date
df_groupped['pre_date'] = df_groupped['Order_Date'].shift(1)
# Calculate previous date of customers
df_groupped['pre_date_customer'] = df_groupped['count_customer'].shift(1)
df_groupped['count_diff_customer'] = df_groupped['count_customer'] - df_groupped['pre_date_customer']
df_groupped

,Order_Date,count_customer,pre_date,pre_date_customer,count_diff_customer
0,2023-01-01,1,NaT,NaN,NaN
1,2023-01-02,4,2023-01-01,1.0,3.0
2,2023-01-03,3,2023-01-02,4.0,-1.0
3,2023-01-04,1,2023-01-03,3.0,-2.0
4,2023-01-05,3,2023-01-04,1.0,2.0
...,...,...,...,...,...
340,2023-12-27,3,2023-12-26,3.0,0.0
341,2023-12-28,3,2023-12-27,3.0,0.0
342,2023-12-29,2,2023-12-28,3.0,-1.0
343,2023-12-30,2,2023-12-29,2.0,0.0
344,2023-12-31,2,2023-12-30,2.0,0.0

## PRACTICE 5:
## Description
> Use the e-commerce dataset and perform the following tasks:

1. Calculate Average Rating and Number of Reviews by Product Categories
Hint: Group the data by product categories. Use aggregation functions like mean() for the average rating and count() for the number of reviews.
2. Number of Orders, and Sales by Product Categories
Hint: Group by product categories and calculate the total number of orders, and total sales (payment_value).
3. Which States Have the Highest Number of Customers?
Hint: Group the data by the state and count the number of distinct customers. You can use groupby() and nunique() to count unique customers by state.
4. Top 5 Customers Generating the Most Revenue
Hint: Group by customer and sum the total revenue (payment_value). Sort the results in descending order and select the top 5.
5. umber of Orders for Each Category (“Morning”, “Afternoon”, “Evening”, “Night”)
Categorize purchase time based on the order_purchase_timestamp hour:
+ “Morning” for hours between 5 AM and 12 PM.
+ “Afternoon” for hours between 12 PM and 5 PM.
 “Evening” for hours between 5 PM and 9 PM.
+ “Night” for hours between 9 PM and 5 AM.
Hint: Categorize the purchase time based on the order_purchase_timestamp hour. Use the .dt accessor to extract the hour, then categorize the hour into “Morning”, “Afternoon”, “Evening”, or “Night”.
6. Total Number of Orders, and Sales by Day of the Week
Hint: Extract the day of the week from the order_purchase_timestamp and group by this day. You can use .dt.day_name() or .dt.weekday to get the day name.
7. Average Rating Based on the Difference Between the Estimated and Actual Delivery Dates
Hint:
+ Calculate the difference between the order_estimated_delivery_date and the order_delivered_customer_date in terms of days.
+ Categorize the delivery status based on the following conditions:
+ If the difference is more than 10 days, categorize it as “late over 10 days”.
+ If the difference is between 5 and 10 days, categorize it as “late from 5 days to 10 days”.
+ If the difference is less than 5 days, categorize it as “late under 5 days”.
+ If the difference is 0 or greater, categorize it as “on time delivery”.
+ Calculate the average rating based on the est_to_deliver_detail column.
Notes:

### Make sure to check the datatype of the columns you are working with, especially dates. You may need to use pd.to_datetime() for conversion.
### For categorizing timestamps or dates, use .dt to extract the components such as day, hour, or month.
### When performing aggregations, use groupby() to group by the relevant column and apply aggregation functions such as mean(), sum(), count(), or nunique().